Ecommerce_Intern/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path ,include
from django.contrib.auth.views import LogoutView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view,AddressUpdateView
#from carts.views import cart_home
#from products.views import ProductDetailSlugView
from accounts.views import LoginView,RegisterView,guest_register_view,BusinessDetailUpdateView,join_us_page,AddSupplierbankdetailView,AddSupplierpersonaldetailView,BankDetailUpdateView
from billing.views import payment_method_view,payment_method_createview,CardUpdateView
from products.views import SupplierHomeView,my_productsView,ProductDetailUpdateView,ReviewView,SupplierReviewView,SupplierProductListView,SupplierAddProductImageView,SupplierAddProductVariationsView,SupplierAddProductQuantityView,SupplierTagView,ProductRefundView,SupplierRentalPeriodView,load_sub_category,load_sub_sub_category
#from carts.views import cart_detail_api_view
#from products.views import OtherDetailFormView
from analytics.views import SalesView,SalesAjaxView,Supplier_SalesView,Supplier_SalesAjaxView
from .views import home_page, about_page, contact_page,notification_page,supplier_notification_page,GeneratePdf,GenerateSupplierPdf,landing_page,home_redirect,order_current_status_notification_page,order_notification_page,low_quantity_notification_page,supplier_order_current_status_notification_page
from orders.views import RequestCancelView
from django.conf.urls.i18n import i18n_patterns
from .views import change_language
admin.site.site_header = 'ShopNow Administration'
admin.site.site_title = 'ShopNow Administration'
admin.site.index_title = 'ShopNow Administration'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('change_language/', 
         change_language, 
         name='change_language'),
]


urlpatterns += i18n_patterns(
    
    
    path('', landing_page, name='landing-page'),
    path('home/',home_redirect, name='home-redirect'),
    path('home/Tokyo/',home_page, name='home'),
    path('home/Osaka/',home_page, name='home1'),
    path('home/Kyoto/',home_page, name='home2'),
    #path('selection_notification_page/',selection_of_notification_page,name='selection_notification_page'),
    path('notification_page/',notification_page,name='notification_page'),
    path('order_notification_page/',order_notification_page,name='order_notification_page'),
    path('order_current_status_notification_page/',order_current_status_notification_page,name='order_current_status_notification_page'),
    path('supplier_notification_page/',supplier_notification_page,name='supplier_notification_page'),
    path('low_quantity_notification_page/',low_quantity_notification_page,name='low_quantity_notification_page'),
    path('supplier_order_current_status_notification_page/',supplier_order_current_status_notification_page,name='supplier_order_current_status_notification_page'),
    path('contact/',contact_page, name='contact'),
    path('notification/', include(("notification.urls", 'notification'), namespace='notification')),
    path('cart/', include(("carts.urls", 'carts'), namespace='cart')),
    path('about/',about_page, name='about'),
    path('join-us/',join_us_page,name='join_us'),
    path('accounts/',RedirectView.as_view(url='/account')),
    path('accounts/',include(("accounts.passwords.urls"))),
    path('account/',include(("accounts.urls", 'accounts'), namespace='account')),
    path('manage/sales/',SalesView.as_view(),name='sales-analytics'),
    path('manage/sales/data/',SalesAjaxView.as_view(),name='sales-analytics-data'),
    path('supplier/sales/',Supplier_SalesView.as_view(),name='supplier-sales-analytics'),
    path('supplier/sales/data/',Supplier_SalesAjaxView.as_view(),name='supplier-analytics-data'),
    path('login/',LoginView.as_view(), name='login'),
    #path('loginsupplier/',SupplierLoginView.as_view(), name='login1'),
    #path('api/cart/',cart_detail_api_view, name='api_cart'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('addressupdate/<int:id>/', AddressUpdateView.as_view(), name='address_update_view'),
    #path('cart/transaction/', TransactionMessageView.as_view() , name='transactionmessage'),
    path('register/guest/',guest_register_view, name='guest_register'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('cardupdate/<int:id>/', CardUpdateView.as_view(), name='card_update_view'),
    # path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('register/',RegisterView.as_view(), name='register'),
    #path('logout_page/', logout_page, name='logout_page'),
    path('settings/',RedirectView.as_view(url='/account')),
    path('products/', include(("products.urls", 'products'), namespace='products')),
    path('orders/', include(("orders.urls", 'orders'), namespace='orders')),
    path('search/', include(("search.urls", 'search'), namespace='search')),
    path('category/', include(("category.urls", 'category'), namespace='category')),
    path('supplier/',SupplierHomeView.as_view(),name='supplier'),
    #path('add/',AddProductView.as_view(),name='add'),
    path('myproduct/',my_productsView.as_view(), name='myproduct'),
    path('updateproduct/<slug:slug>/',ProductDetailUpdateView.as_view(),name='update'),
    #path('products/<slug:slug>/',ProductDetailSlugView.as_view(),name='other'),
    path('request-refund/<int:id>/<slug:slug>/',RequestCancelView.as_view(),name='refund'),
    path('reviews/<int:id>/<slug:slug>/',ReviewView.as_view(),name='review'),
    path('product-refund/<int:id>/<slug:slug>/',ProductRefundView.as_view(),name='product-refund'),
    path('supplierreviews/',SupplierReviewView.as_view(),name='supplierreview'),
    path('businessdetailupdate/',BusinessDetailUpdateView.as_view(),name='businessdetailupdate'),
    path('bankdetailupdate/',BankDetailUpdateView.as_view(),name='bankdetailupdate'),
    path('addpersonaldetails/',AddSupplierpersonaldetailView.as_view(),name='addsupplierpersonaldetail'),
    path('addbankaccountdetails/',AddSupplierbankdetailView.as_view(),name='addsupplierbankdetail'),
    #path('add_product/',SupplierAddProductView.as_view(),name='addproduct'),
    path('add_product_details/',SupplierProductListView.as_view(),name='addproductdetails'),
    path('add_product_details/add_image/<int:id>/',SupplierAddProductImageView.as_view(),name='productimage'),
    path('add_product_details/add_variations/<int:id>/',SupplierAddProductVariationsView.as_view(),name='productvariations'),
    path('add_product_details/add_quantity/<int:id>/',SupplierAddProductQuantityView.as_view(),name='productquantity'),
    path('add_product_details/add_tags/<int:id>/',SupplierTagView.as_view(),name='producttags'),
    path('add_product_details/add_rental_period/<int:id>/',SupplierRentalPeriodView.as_view(),name='productrentalperiods'),
    path('<order_id>/pdf/',GeneratePdf.as_view(),name='pdf'),
    path('<id>/<order_id>/supplier/pdf/',GenerateSupplierPdf.as_view(),name='supplierpdf'),
    #prefix_default_language = False,
    path('load-sub_category/', load_sub_category, name='ajax_load_sub_category'), # AJAX
    path('load-sub_sub_category/', load_sub_sub_category, name='ajax_load_sub_sub_category'), # AJAX


)

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.contrib import admin
from django.urls import path
from .views import cart_home,checkout_home,checkout_done_view,add_to_cart,remove_cart,remove_all_items,payment_method_default_update_view,remove_coupon_view


urlpatterns = [
   
    path('',cart_home, name='home'),
    #path('<slug:slug>/',update_cart, name='update_cart'),
    path('remove/<int:id>/', remove_cart, name='remove_cart'),
    path('removeall/', remove_all_items, name='remove_all'),
    path('<int:id>/', add_to_cart, name='add_to_cart'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('checkout/', checkout_home, name='checkout'),
    path('reusecards/', payment_method_default_update_view, name='reusecard'),
    path('removecoupon/<int:id>', remove_coupon_view, name='removecoupon')
]

products/urls.py
from django.contrib import admin
from django.urls import path
from .views import product_list_view,ProductDetailSlugView,ProductImageUpdateView,my_productsimageView,my_productsquantityView,ProductQuantityUpdateView
from .views import category_product_view_1,sub_category_product_view,sub_sub_category_product_view
from .views import remove_rentalperiod,remove_variations,remove_quantity,remove_image,remove_tags
#from .views import  product_list_sort_by_low_to_high_view, product_list_sort_by_high_to_low_view


urlpatterns = [
   
    path('',product_list_view, name='list'),
    #path('low_to_high/',product_list_sort_by_low_to_high_view, name='low_to_high'),
    #path('high_to_low/',product_list_sort_by_high_to_low_view, name='high_to_low'),
    path('<slug:slug>/',ProductDetailSlugView.as_view(), name='detail'),
    path('image/<slug:slug>/',my_productsimageView.as_view(),name='image'),
    path('quantity/<slug:slug>/',my_productsquantityView.as_view(),name='quantity'),
    path('quantity/update/<int:id>/',ProductQuantityUpdateView.as_view(),name='quantityupdate'),
    path('image/update/<int:id>/',ProductImageUpdateView.as_view(),name='imageupdate'),
    path('remove/<int:id1>/<int:id>/',remove_rentalperiod,name='remove_rentalperiod'),
    path('removevariations/<int:id1>/<int:id>/',remove_variations,name='remove_variations'),
    path('removequantity/<int:id1>/<int:id>/',remove_quantity,name='remove_quantity'),
    path('removeimage/<int:id1>/<int:id>/',remove_image,name='remove_image'),
    path('removetags/<int:id1>/<int:id>/',remove_tags,name='remove_tags'),
    #path('other/<slug:slug>/',OtherDetailFormView.as_view(),name='other'), 
    path('category/<slug:slug>/',category_product_view_1 , name='query'),
    path('sub_category/<slug:slug>/',sub_category_product_view , name='query1'),
    path('sub_sub_category/<slug:slug>/',sub_sub_category_product_view , name='query2'),
    # path('Novels',category_product_view_2 , name='query_1'),
    # path('instruments',category_product_view_3 , name='query_3'),
    # path('Accessories',category_product_view_4 , name='query_4'),
    # path('sub_category/<slug>/<color>/',sub_category_product_view_by_color,name='query_5'),
    # path('sub_sub_category/<slug:slug>/<color>/',sub_sub_category_product_view_by_color,name='query_6'),
    # path('sub_category/size/<slug:slug>/<size>/',sub_category_product_view_by_size,name='size_sub_query'),
    # path('sub_sub_category/<slug:slug>/<size>/',sub_sub_category_product_view_by_size,name='size_sub_sub_query'),
    
   

]

catogary/views.py
from django.shortcuts import render,redirect
from products.models import Product_description,Category
from django.views.generic import ListView




def catogary_product_view(request, slug,*args, **kwargs):
    
    try:
        query = Category.objects.get(slug=slug)
    except Category.DoesNotExist:
        print("Product does not exist now!")
        return redirect("products:list")
    
    print(query)
    if query is not None:
        queryset = Product_description.objects.filter(categary=query)
    else:
        queryset=Product_description.objects.all()
    context = {
          'qs': queryset ,
          'q': query,
          #'clothing_category': query,
         "title":"Products",
    }
    # def get_context_data(self,*args, **kwargs):
    #     context=super(catogary_product_view ,self).get_context_data(*args, **kwargs)
    #     query=self.request.GET.get("query")
    #     context['query']=query
    #     #SearchQuery.objects.create(query=query)
    #     return context

    return render(request,"products/view.html", context)

products/templates/products/snippets/card.html
{% load staticfiles %}
<!-- <div class="card" style="width: 18rem">
   {% if instance.image %}
  <a href="{{ instance.get_absolute_url }}" ><img src="{{ instance.image.url }}" class="card-img-top" alt="{{ instance.title }} logo">
  </a>
  {% else %}
  <img class='image-responsive' src='{% static "img/placeholder.png" %}'/>
  {% endif %}
  <div class="card-body">
    <h5 class="card-title"></h5>
    <h5 class="card-title"> {{ instance.product_name|capfirst }}</h5>
    <h6 class="card-title"> {% if instance.discount_price %}
            <strike> ${{ instance.cost_per_day }}</strike> ${{ instance.discount_price }}/day ({{ instance.get_amount_percent_saved }}% Off)
           {% else %}
           ${{ instance.cost_per_day }}/day
           {% endif %}
           </h6>
    <p class="card-text">{{ instance.description|linebreaks|truncatewords:14 }}</p>
    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">View! </a>



  </div>
</div> -->
<style>
              @media screen and ( max-width: 992px) {
                #car1 {
                  width: 15em !important;


                }
              }
              @media only screen and (min-width: 1200px) {
                #car1 {
                  width: 15rem !important;
              }
              }

              /* On screens that are 600px or less, set the background color to olive */
              @media screen and (max-width: 600px) {
                #car1 {
                  width: auto !important;

            }
          }

        .checked {
          color: orange;
        }
        .card:hover {
              -ms-transform: scale(1.15); /* IE 9 */
              -webkit-transform: scale(1.15); /* Safari 3-8 */
              transform: scale(1.15);
               transition: transform .2s;
            }

  </style>

        <div id=car1 class="card m-0 p-0 h-100">

              <!--Card image-->
              <div class="view">
                 {% if instance.image %}
                 <a href="{{ instance.get_absolute_url }}" target="_blank" ><img src="{{ instance.image.url }}" class="card-img-top" alt="{{ instance.title }} logo">
                   </a>
                  {% else %}
                  <img class='card-img-top' src='{% static "img/placeholder.png" %}'/>
                  {% endif %}

                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
              {% if instance.rating >= 1 %}
              ({{ instance.rating }})
              {% endif %}
                {% if instance.rating >= 1 and instance.rating < 2 %}
          <span class="fa fa-star checked"></span>
            <span class="fa fa-star-o"></span>
            <span class="fa fa-star-o"></span>
            <span class="fa fa-star-o"></span>
            <span class="fa fa-star-o"></span>
            {% endif %}

            {% if instance.rating >= 2 and instance.rating < 3 %}
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star-o"></span>
          <span class="fa fa-star-o"></span>
          <span class="fa fa-star-o"></span>
            {% endif %}
          {% if instance.rating >= 3 and instance.rating < 4 %}
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star-o"></span>
          <span class="fa fa-star-o"></span>
            {% endif %}
          {% if instance.rating >= 4 and instance.rating < 4.5 %}
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star-o"></span>
            {% endif %}
          {% if  instance.rating >= 4.5 and instance.rating <= 5 %}
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
        {% endif %}
                 <h6 class="card-title text-grey"> {{ instance.category|capfirst }},{{ instance.brand|capfirst }}</h6>


                <h5>
                  <strong>
                    <a href="{{ instance.get_absolute_url }}" target="_blank"><div class="text-grey">{{ instance.product_name|capfirst }}</div></a>
                     {% for t in trending %}
                     {% if t.product.id == instance.id %}
                      <span class="badge badge-pill badge-primary">Trending</span>
                      {% endif %}
                      {% endfor %}
                      {% if instance.timestamp >= instance.product_posted_days %}

                      <span class="badge badge-pill badge-danger">NEW</span>

                      {% endif %}

                  </strong>
                </h5>

                <h6 class="font-weight-bold blue-text">
                <strong>  {% if instance.discount_price %}
            <strike> ${{ instance.cost_per_day }}</strike> ${{ instance.discount_price }}/day ({{ instance.get_amount_percent_saved }}% Off)
           {% else %}
           ${{ instance.cost_per_day }}/day
           {% endif %}

           </strong>
                </h6>

              </div>
              <!--Card content-->

            </div>

products/templates/products/snippets/catogary.html
{% load static %}
{% url 'products:query_3' as category_list_url_2 %}
{% url 'products:query' as category_list_url_1 %}
{% url 'products:query_1' as category_list_url %}


  <div class='card-columns'>
  <div class="card" style="width:300px">
 <a href="{{ category_list_url }}" ><img class="card-img-top" src="{% static 'img/b.jpg' %}"  alt="Card image"  ></a>
  <div class="card-body" >
    <h4 class="card-title">Books/novels corner</h4>
    <p>Want to read latest and famous Novels.</p>
   </div>
   </div>
   
    <!-- <a href="#" class="btn btn-primary">See Profile</a> -->
  
  <div class="card" style="width:300px">
  <a href="{{ category_list_url_1 }}" ><img class="card-img-top" src="{% static 'img/a.jpg' %}" alt="Card image"></a>
  <div class="card-body">
       <h4 class="card-title">Clothing</h4>
    <p class="card-text">Latest releases </p>
  </div>
  </div>
  <div></div>

  <div class="card" style="width:300px">
   <a href="{{ category_list_url_2 }}" ><img class="card-img-top" src="{% static 'img/c.jpg' %}" alt="Card image"></a>
  <div class="card-body">
    <h4 class="card-title">Musical Instruments</h4>
    <p class="card-text">Want to try Learn musical Instruments? </p>
    <!-- <a href="#" class="btn btn-primary">See Profile</a> -->
  </div>
  </div>

products/templates/products/snippets/product_card.html
{% load staticfiles %}
    <style>
              

          .checked {
                  color: orange;
                }
    </style>
<div class="container" style="background-color: #ffffff">
 <div class='row'>
  {% if instance.image %}
  <img src="{{ instance.image.url }}" class="card-img-top pt-2 pl-2" style="height:100px;width:100px" alt="{{ instance.title }} logo">
  
  {% endif %}
  <div class="card-body text-center">
    
       {% if instance.rating >= 1 %}
              ({{ instance.rating }})
              {% endif %}
                {% if instance.rating >= 1 and instance.rating < 2 %}
          <span class="fa fa-star checked"></span>
            <span class="fa fa-star-o"></span>
            <span class="fa fa-star-o"></span>
            <span class="fa fa-star-o"></span>
            <span class="fa fa-star-o"></span>
            {% endif %}

            {% if instance.rating >= 2 and instance.rating < 3 %}
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star-o"></span>
          <span class="fa fa-star-o"></span>
          <span class="fa fa-star-o"></span>
            {% endif %}
          {% if instance.rating >= 3 and instance.rating < 4 %}
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star-o"></span>
          <span class="fa fa-star-o"></span>
            {% endif %}
          {% if instance.rating >= 4 and instance.rating < 4.5 %}
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star-o"></span>
            {% endif %}
          {% if  instance.rating >= 4.5 and instance.rating <= 5 %}
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
        {% endif %} 
                    
    <h5 class="card-title"> {{ instance.product_name|capfirst }}</h5>
     <h6 class="card-title"> {% if instance.discount_price %}
            <strike> ${{ instance.cost_per_day }}</strike> ${{ instance.discount_price }}/day ({{ instance.get_amount_percent_saved }}% Off)
           {% else %}
           ${{ instance.cost_per_day }}/day
           {% endif %}
           </h6>
    <p class="card-text">{{ instance.description|linebreaks|truncatewords:14 }}</p>
    <a href="{{ instance.get_absolute_url1 }}" class="btn mb-2" style='background-color: #1daf9e; color:#ffffff;'>Update product details </a>
    <a href="{% url 'products:image' instance.slug %}" class="btn mb-2" style='background-color: #1daf9e; color:#ffffff;'>Update product images </a>
    <a href="{% url 'products:quantity' instance.slug %}" class="btn mb-2" style='background-color: #1daf9e; color:#ffffff;'>Update product quantity </a>

    
    
  </div>  
  </div>
</div>

products/templates/products/snippets/supplier_changeproduct_details_card.html
{% load staticfiles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/progressbar.css' %}">
<div class="container" style="background-color:#ffffff">
   {% if instance.image %}
  <a href='{% url "myproduct" %}' ><img src="{{ instance.image.url }}" class="card-img-top " title='Update the product details, Click here' style="height:100px;width:100px" alt="{{ instance.title }} logo">
  </a>
  {% else %}
  <img class='image-responsive' src='{% static "img/placeholder.png" %}'/>
  {% endif %}
  <div class='text-right'>
    <a href='{% url "productvariations" instance.id %}' class=" btn mb-2" style='background-color: #1daf9e; color:#ffffff;'>Add product details<i title="Please add more details of product."  class="fas fa-question-circle"></i> </a>
</div>
  
  <div class="card-body">
    <h5 class="card-title"></h5>
    <h5 class="card-title"> {{ instance.product_name|capfirst }}</h5>
    <h6 class="card-title"> {% if instance.discount_price %}
            <strike> ${{ instance.cost_per_day }}</strike> ${{ instance.discount_price }}/day ({{ instance.get_amount_percent_saved }}% Off)
           {% else %}
           ${{ instance.cost_per_day }}/day
           {% endif %}
           </h6>
    <p class="card-text">{{ instance.description|linebreaks|truncatewords:14 }}</p>
    
   <p>If already added the images, quantity, tags, color and sizes below?, then <a  href='{% url "myproduct" %}'>  update these details here. </a> </p>
   
    <!-- <a href='{% url "productimage" instance.id %}'  class=" btn btn-primary mb-2">2. Add more images <i title="Add more images for better showup to users" class="fas fa-question-circle"></i> </a>
    <a href='{% url "productquantity" instance.id %}' class=" btn btn-danger mb-2">3. Add quantity <i title='Add quantity for each variations of product.' class="fas fa-question-circle"></i> </a> 
    <a href='{% url "producttags" instance.id %}' class="btn btn-success mb-2">4. Add product tags <i title='Add all the product tags that can be possible for the product.' class="fas fa-question-circle"></i> </a> 
    <a href='{% url "productrentalperiods" instance.id %}' class="btn btn-success mb-2">5. Add Rental Period <i title='Add all the product rental period.' class="fas fa-question-circle"></i> </a>  -->
    
    
    
  </div>

</div>