Ecommerce_Intern/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path ,include
from django.contrib.auth.views import LogoutView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view,AddressUpdateView
#from carts.views import cart_home
#from products.views import ProductDetailSlugView
from accounts.views import LoginView,RegisterView,guest_register_view,BusinessDetailUpdateView,join_us_page,AddSupplierbankdetailView,AddSupplierpersonaldetailView,BankDetailUpdateView
from billing.views import payment_method_view,payment_method_createview,CardUpdateView
from products.views import SupplierHomeView,my_productsView,ProductDetailUpdateView,ReviewView,SupplierReviewView,SupplierProductListView,SupplierAddProductImageView,SupplierAddProductVariationsView,SupplierAddProductQuantityView,SupplierTagView,ProductRefundView,SupplierRentalPeriodView,load_sub_category,load_sub_sub_category
#from carts.views import cart_detail_api_view
#from products.views import OtherDetailFormView
from analytics.views import SalesView,SalesAjaxView,Supplier_SalesView,Supplier_SalesAjaxView
from .views import home_page, about_page, contact_page,notification_page,supplier_notification_page,GeneratePdf,GenerateSupplierPdf,landing_page,home_redirect,order_current_status_notification_page,order_notification_page,low_quantity_notification_page,supplier_order_current_status_notification_page
from orders.views import RequestCancelView
from django.conf.urls.i18n import i18n_patterns
from .views import change_language
admin.site.site_header = 'ShopNow Administration'
admin.site.site_title = 'ShopNow Administration'
admin.site.index_title = 'ShopNow Administration'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('change_language/', 
         change_language, 
         name='change_language'),
]


urlpatterns += i18n_patterns(
    
    
    path('', landing_page, name='landing-page'),
    path('home/',home_redirect, name='home-redirect'),
    path('home/Tokyo/',home_page, name='home'),
    path('home/Osaka/',home_page, name='home1'),
    path('home/Kyoto/',home_page, name='home2'),
    #path('selection_notification_page/',selection_of_notification_page,name='selection_notification_page'),
    path('notification_page/',notification_page,name='notification_page'),
    path('order_notification_page/',order_notification_page,name='order_notification_page'),
    path('order_current_status_notification_page/',order_current_status_notification_page,name='order_current_status_notification_page'),
    path('supplier_notification_page/',supplier_notification_page,name='supplier_notification_page'),
    path('low_quantity_notification_page/',low_quantity_notification_page,name='low_quantity_notification_page'),
    path('supplier_order_current_status_notification_page/',supplier_order_current_status_notification_page,name='supplier_order_current_status_notification_page'),
    path('contact/',contact_page, name='contact'),
    path('notification/', include(("notification.urls", 'notification'), namespace='notification')),
    path('cart/', include(("carts.urls", 'carts'), namespace='cart')),
    path('about/',about_page, name='about'),
    path('join-us/',join_us_page,name='join_us'),
    path('accounts/',RedirectView.as_view(url='/account')),
    path('accounts/',include(("accounts.passwords.urls"))),
    path('account/',include(("accounts.urls", 'accounts'), namespace='account')),
    path('manage/sales/',SalesView.as_view(),name='sales-analytics'),
    path('manage/sales/data/',SalesAjaxView.as_view(),name='sales-analytics-data'),
    path('supplier/sales/',Supplier_SalesView.as_view(),name='supplier-sales-analytics'),
    path('supplier/sales/data/',Supplier_SalesAjaxView.as_view(),name='supplier-analytics-data'),
    path('login/',LoginView.as_view(), name='login'),
    #path('loginsupplier/',SupplierLoginView.as_view(), name='login1'),
    #path('api/cart/',cart_detail_api_view, name='api_cart'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('addressupdate/<int:id>/', AddressUpdateView.as_view(), name='address_update_view'),
    #path('cart/transaction/', TransactionMessageView.as_view() , name='transactionmessage'),
    path('register/guest/',guest_register_view, name='guest_register'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('cardupdate/<int:id>/', CardUpdateView.as_view(), name='card_update_view'),
    # path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('register/',RegisterView.as_view(), name='register'),
    #path('logout_page/', logout_page, name='logout_page'),
    path('settings/',RedirectView.as_view(url='/account')),
    path('products/', include(("products.urls", 'products'), namespace='products')),
    path('orders/', include(("orders.urls", 'orders'), namespace='orders')),
    path('search/', include(("search.urls", 'search'), namespace='search')),
    path('category/', include(("category.urls", 'category'), namespace='category')),
    path('supplier/',SupplierHomeView.as_view(),name='supplier'),
    #path('add/',AddProductView.as_view(),name='add'),
    path('myproduct/',my_productsView.as_view(), name='myproduct'),
    path('updateproduct/<slug:slug>/',ProductDetailUpdateView.as_view(),name='update'),
    #path('products/<slug:slug>/',ProductDetailSlugView.as_view(),name='other'),
    path('request-refund/<int:id>/<slug:slug>/',RequestCancelView.as_view(),name='refund'),
    path('reviews/<int:id>/<slug:slug>/',ReviewView.as_view(),name='review'),
    path('product-refund/<int:id>/<slug:slug>/',ProductRefundView.as_view(),name='product-refund'),
    path('supplierreviews/',SupplierReviewView.as_view(),name='supplierreview'),
    path('businessdetailupdate/',BusinessDetailUpdateView.as_view(),name='businessdetailupdate'),
    path('bankdetailupdate/',BankDetailUpdateView.as_view(),name='bankdetailupdate'),
    path('addpersonaldetails/',AddSupplierpersonaldetailView.as_view(),name='addsupplierpersonaldetail'),
    path('addbankaccountdetails/',AddSupplierbankdetailView.as_view(),name='addsupplierbankdetail'),
    #path('add_product/',SupplierAddProductView.as_view(),name='addproduct'),
    path('add_product_details/',SupplierProductListView.as_view(),name='addproductdetails'),
    path('add_product_details/add_image/<int:id>/',SupplierAddProductImageView.as_view(),name='productimage'),
    path('add_product_details/add_variations/<int:id>/',SupplierAddProductVariationsView.as_view(),name='productvariations'),
    path('add_product_details/add_quantity/<int:id>/',SupplierAddProductQuantityView.as_view(),name='productquantity'),
    path('add_product_details/add_tags/<int:id>/',SupplierTagView.as_view(),name='producttags'),
    path('add_product_details/add_rental_period/<int:id>/',SupplierRentalPeriodView.as_view(),name='productrentalperiods'),
    path('<order_id>/pdf/',GeneratePdf.as_view(),name='pdf'),
    path('<id>/<order_id>/supplier/pdf/',GenerateSupplierPdf.as_view(),name='supplierpdf'),
    #prefix_default_language = False,
    path('load-sub_category/', load_sub_category, name='ajax_load_sub_category'), # AJAX
    path('load-sub_sub_category/', load_sub_sub_category, name='ajax_load_sub_sub_category'), # AJAX


)

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/passwords/urls.py
# accounts.passwords.urls.py 

from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from products.models import Category,Sub_Category,Sub_Sub_Category

urlpatterns  = [
                path('password/change/',auth_views.PasswordChangeView.as_view(extra_context={"category_images": Category.objects.all(), "sub_categorys": Sub_Category.objects.all(), "sub_sub_categorys": Sub_Sub_Category.objects.all()}), name='password_change'),
                path('password/change/done/',auth_views.PasswordChangeDoneView.as_view(extra_context={"category_images": Category.objects.all(), "sub_categorys": Sub_Category.objects.all(), "sub_sub_categorys": Sub_Sub_Category.objects.all()}), name='password_change_done'),
                path('password/reset/',auth_views.PasswordResetView.as_view(extra_context={"category_images": Category.objects.all(), "sub_categorys": Sub_Category.objects.all(), "sub_sub_categorys": Sub_Sub_Category.objects.all()}), name='password_reset'),
                path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(extra_context={"category_images": Category.objects.all(), "sub_categorys": Sub_Category.objects.all(), "sub_sub_categorys": Sub_Sub_Category.objects.all()}),name='password_reset_done'),
                path('password/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(extra_context={"category_images": Category.objects.all(), "sub_categorys": Sub_Category.objects.all(), "sub_sub_categorys": Sub_Sub_Category.objects.all()}),name='password_reset_confirm'),
                path('password/reset/complete/',auth_views.PasswordResetCompleteView.as_view(extra_context={"category_images": Category.objects.all(), "sub_categorys": Sub_Category.objects.all(), "sub_sub_categorys": Sub_Sub_Category.objects.all()}), name='password_reset_complete')
]

accounts/urls.py
from django.contrib import admin
from django.urls import path
from products.views import UserProductHistoryView
from .views import AccountHomeView, UserDetailUpdateView,AccountEmailActivateView


urlpatterns = [
   
    path('', AccountHomeView.as_view(), name='home'),
    path('email/confirm/<key>/', AccountEmailActivateView.as_view(), name='email-activate'),
    path('email/resend-activation/', AccountEmailActivateView.as_view(), name='resend-activation'),
    path('details/', UserDetailUpdateView.as_view(), name='user-update'),
    path('history/products/',UserProductHistoryView.as_view(),name='user-product-history'),
   
]

carts/urls.py
from django.contrib import admin
from django.urls import path
from .views import cart_home,checkout_home,checkout_done_view,add_to_cart,remove_cart,remove_all_items,payment_method_default_update_view,remove_coupon_view


urlpatterns = [
   
    path('',cart_home, name='home'),
    #path('<slug:slug>/',update_cart, name='update_cart'),
    path('remove/<int:id>/', remove_cart, name='remove_cart'),
    path('removeall/', remove_all_items, name='remove_all'),
    path('<int:id>/', add_to_cart, name='add_to_cart'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('checkout/', checkout_home, name='checkout'),
    path('reusecards/', payment_method_default_update_view, name='reusecard'),
    path('removecoupon/<int:id>', remove_coupon_view, name='removecoupon')
]

accounts/templates/accounts/business-detail-update-view.html
{% extends "supplier_base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/progressbar.css' %}">
<link rel="stylesheet" href="{% static 'css/form.css' %}">


<div class='col'>
<div class='container'  style='background-color:#ffffff;'>
    <div class="col-12 col-md-6 mx-auto">
        {% if title %} <h1>{{ title }}</h1> {% endif %}
<form  method='POST' action='{% if action_url %} {{ action_url }}{% endif %}'>
     {% csrf_token %}
     {% if next_url %}
     <input type='hidden' name='next' value='{{ next_url }}' />
     {% endif %}
    

     {{ form|crispy }}<br/>
     <label for='email'>Email</label>
     <input type='text' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /> <br/>
     <div class='text-center'>
<button type='submit' class='btn-bg btn' style='background-color: #1daf9e; color:white;'> Update </button>
     </div>
     <br/>
</form>
</div>
</div>


</div>
</div>
</div>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script><script  src="{% static 'js/vertical-nav.js' %}"></script>

{% endblock %}

accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br/>
<link rel="stylesheet" href="{% static 'css/form.css' %}">
<head>
<!-- <style media="screen">
  body {
    background-color: #f7f7f7 !important;
  }
  ol.breadcrumb {
    font-size: 80%;
    background: #fafafa;
  }
  ol.breadcrumb li+li:before {
    color: black;
    content: ">" !important;
  }
  ol.breadcrumb li a {
    color: #7f7f7f;
    text-decoration: none;
  }
  ol.breadcrumb li.active {
    color: #7f7f7f;
    font-weight: bold;
  }
  span.input-group-text {
    border-radius: 4px;
    border-color: #f6fcfb;
    background-color: #f6fcfb;
    font-size: 90%
  }
  input.form-control {
    border-radius: 4px;
    border-color: #f6fcfb;
    background-color: #f6fcfb;
    font-size: 90%;
    color: #68cfc3 !important;
    outline: none !important;
    box-shadow: none;
  }
  .form-control:focus {
    border: none;
    background-color: #f6fcfb;
    box-shadow: 0 0 0 0rem rgba(40, 167, 69, 0.25);
  }
  ::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
    color: #68cfc3;
    opacity: 1; /* Firefox */
  }

  :-ms-input-placeholder { /* Internet Explorer 10-11 */
    color: #68cfc3;
  }

  ::-ms-input-placeholder { /* Microsoft Edge */
    color: #68cfc3;
  }
</style> -->
</head>

<body>
  <div class="container-fluid" style="background-color: #fafafa !important;">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">ホーム</a></li>
          <li class="breadcrumb-item active" aria-current="page">ログイン</li>
        </ol>
      </nav>
    </div>
  </div>
  <div class="container">
    <div class="container" style="background: #e06a3b">
      <p style="color: #fff; text-align: center">会員情報の変更内容を登録しました。</p>
    </div>
  </div>
  <div class="container">
    <div class="container p-0">
      <p class="pb-3" style="color: #555555; font-size: 130%; font-weight: bold;">登録情報</p>
    </div>
  </div>
  <div class="container p-3">
<div class='container' style='background-color:#ffffff ; color: black'>
    <div class="col-12 col-md-6 mx-auto">
        {% if title %} <h2 class='my-3 py-3 text-center'>{{ title }}</h2> {% endif %}
       
<form  method='POST' enctype="multipart/form-data" action='{% if action_url %} {{ action_url }}{% endif %}'>
     {% csrf_token %}
     {% if form.errors %}
       <h6>Sorry your image size is greater than 1 MB.please upload image <= 1 MB.</h6>
       {% endif %}
     {% if next_url %}
     <input type='hidden' name='next' value='{{ next_url }}' />
     {% endif %}
    <div class='text-center'>
       
        {% if object.profile_image %}
                <img src="{{ object.profile_image.url }}" class="rounded-circle z-depth-0"
                  alt="avatar image" height="100" width="100" />
            
                  {% else %}
                  <img src='{% static "img/images.jpg" %}' class="rounded-circle z-depth-0"
                  alt="avatar image" height="100" width="100" />
        {% endif %}
                <h6>Note: Please upload image less than 1 MB in size.</h6>
    
    </div>

     {{ form|crispy }}<br/>
     <label for='email'>Email</label>
     <input type='text' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /> <br/>
<div class='text-center'>
<button type='submit' class='btn-lg btn' style='background-color: #e06a3b; color:#ffffff'> Save </button>
<a href='{% url "password_change" %}' ><font color='#1daf9e'>Change Password?</font></a>
</div>
<br/>
</form>
</div>
</div>

</div>
  <div class="container">
    <div class="container p-0">
      <p class="py-3 mt-3" style="color: #555555; font-size: 130%; font-weight: bold;">支払情報</p>
    </div>
  </div>
  {% for card in cards %}
  <div class="container">
    <div class="container p-3" style="background-color: #ffffff;">
      <div class="row p-3">
        <div class="col col-md-2">
          <p class="p-2" style="color: #1daf9e;" >カード{{ forloop.counter }}</p>
        </div>
      </div>
      <div class="row p-3">
        <div class="col">
          <p class="p-2" style="border-radius: 4px; color: #aaaaaa;">{{ card.brand }} {{ card.country }} ********{{ card.last4 }} {{ card.exp_month }}/{{ card.exp_year }}</p>
        </div>
        <div class="col-3 text-right">
          <a href='{% url "card_update_view" card.id %}'>  <button class="p-2 mt-3" style="border-radius: 4px; border: solid 2px #1daf9e; color: #1daf9e; font-size: 80%;">変更</button></a>
        </div>
      </div>
     
      </div>
    </div>
    {% endfor %}
  </div>
 
  <div class="container">
    <div class="container p-0">
      <p class="py-3 mt-3" style="color: #555555; font-size: 130%; font-weight: bold;">Addresses</p>
    </div>
  </div>
  {% for address in addresses %}
  <div class="container">
    <div class="container p-3" style="background-color: #ffffff;">
      <div class="row p-3">
        <div class="col col-md-2">
          <p class="p-2" style="color: #1daf9e;">Address {{ forloop.counter }}</p>
        </div>
      </div>
      <div class="row p-3">
        <div class="col">
          <div class="d-flex flex-row justify-content-between">
            <div class="col">
              <div class="row">
                <p class="p-2" style="border-radius: 4px; color: #aaaaaa;">
                  {{ address.address_type|capfirst }} Address:  {{ address.address_line_1 }} {{ address.city }} {{ address.country }} {{ address.postal_code }} </p>
              </div>
            </div>
           
          </div>
        </div>
        <div class="col-3 text-right">
          <a href='{% url "address_update_view" address.id %}'>  <button class="p-2 mt-3" style="border-radius: 4px; border: solid 2px #1daf9e; color: #1daf9e; font-size: 80%;">変更</button> </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  <div class="container">
    <div class="container p-0">
      <p class="py-3 mt-3" style="color: #555555; font-size: 130%; font-weight: bold;">プロフィール</p>
    </div>
  </div>
  <div class="container">
    <div class="container p-3" style="background-color: #ffffff;">
      <div class="row p-3">
        <div class="col">
          <p class="p-2" style="color: #555;">ニックネーム</p>
          <p class="mt-3 w-50" style="color: #555;">We promise quick and courteous transactions.
              We will show you the goods you have collected as a hobby.
              There is no problem with immediate purchase without confirmation comments.
              Discount
              We do not accept discounts for single items.
              In the case of summary, we will correspond depending on the contents.
              Extreme discounts are not available.
              Some products are not discounted.
              You may not be able to reply immediately
              I will reply as soon as I confirm.</p>
        </div>
      
        <div class="col-3 text-right mt-3">
          <button class="p-2 mt-3" style="border-radius: 4px; border: solid 2px #1daf9e; color: #1daf9e; font-size: 80%;">変更</button>
        </div>
      </div>
    </div>
  </div>
  
</body>
{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}
{% load static i18n %}
{% block content %}

<style media="screen">
  .card:hover {
    transform: scale(1.1) !important; 
  }
</style>
<div class="container" style="background-color: #1daf9e; color: #fff;">
  Welcome {{ request.user.full_name }}!
</div>
<div class='container' style='background-color: white; color: white;'>
<div class='row'>
    <div class='col-12' style="background-color: #1daf9e; color:white;">
        <h2 class='text-center'>{% trans "Account" %}</h2>
        <hr/>
    </div>


<div class='col-12 col-md-4 my-3'>
<div class="card h-100" style="background-color: #1daf9e;">
  <div class="card-body">
    <h5 class="card-title text-center">{% trans "History" %}</h5>
        <a class='list-group-item' style="background-color: #1daf9e; color: white;" href='{% url "account:user-product-history" %}'>{% trans "Products" %} </a>

  </div>
</div>
</div>


<div class='col-12 col-md-4 my-3'>
<div class="card h-100" style="background-color: #1daf9e;">
  <div class="card-body">
    <h5 class="card-title text-center">{% trans "Add new card" %}</h5>
        <a class='list-group-item' style="background-color: #1daf9e; color: white;" href='{% url "billing-payment-method" %}'>{% trans "Payment Methods" %} </a>

  </div>
</div>
</div>



<div class='col-12 col-md-4 my-3'>
<div class="card h-100" style="background-color: #1daf9e;">
  <div class="card-body">
    <h5 class="card-title text-center">{% trans "Support" %}</h5>
      <div class='list-group'>
          <a class='list-group-item' style="background-color: #1daf9e; color:white" href='{% url "about" %}'>{% trans "About" %} </a>
          <a class='list-group-item' style="background-color: #1daf9e; color: white;" href='{% url "contact" %}'>{% trans "Contact" %} </a>
      </div>


  </div>
</div>
</div>

<div class='col-12 col-md-4 my-3'>
<div class="card h-100" style="background-color: #1daf9e;">
  <div class="card-body">
    <h5 class="card-title text-center">{% trans "Personal Info" %}</h5>
        <a class='list-group-item' style="background-color: #1daf9e; color: white;" href='{% url "account:user-update" %}'>{% trans "Update details" %} </a>
          <a class='list-group-item' style="background-color: #1daf9e; color: white;" href='{% url "password_change" %}'> {% trans "ChangePassword" %} </a>

  </div>
</div>
</div>

<div class='col-12 col-md-4 my-3'>
<div class="card h-100" style="background-color: #1daf9e;">
  <div class="card-body">
    <h5 class="card-title text-center">{% trans "Billing" %}</h5>
     <div class='list-group'>
          <a class='list-group-item' style="background-color: #1daf9e; color: white;" href='{% url "orders:list" %}'>{% trans "My Orders(paid)" %} </a>
          <a class='list-group-item' style="background-color: #1daf9e; color: white;" href='{% url "orders:created" %}'>{% trans "My created(unpaid) Orders" %} </a>

            <!-- <a class='list-group-item' href='#'>Addresses </a> -->
      </div>

  </div>
</div>
</div>


</div>
</div>
{% endblock %}

accounts/templates/accounts/join_us.html
{% extends "base.html" %}
{% block content %}
<br/>
<div class='container-fluid' style = "background-color: #263238; color: white">
<h2 class='text-center'>" Some people earned more than <font size=10 >&yen </font>70000/month on E-renta.”</h2>
<h6 class='text-center'>- by e-renta team</h6>
<br/>
<div class='text-center'>
{% if personal_details and bank_details %}
    <a href="{% url 'supplier' %}"><button type='submit' class='btn btn-warning btn-lg'> Welcome, Go to dashboard  </button> </a>
   
{% elif personal_details and not bank_details %}
    <a href="{% url 'addsupplierbankdetail' %}"><button type='submit' class='btn btn-warning btn-lg'> Start as lender  </button> </a>
    
    <h6 class='text-center mt-4'>It only take 5 minutes to setup your account.</h6>
    
{% else %}
    <a href="{% url 'addsupplierpersonaldetail' %}"><button type='submit' class='btn btn-warning btn-lg'> Start as lender  </button> </a>
    
    <h6 class='text-center mt-4'>It only take 5 minutes to setup your account.</h6>
   
{% endif %}

</div>
<br/>
</div>
<div class="text-center">
<h2 style="color: #263238;"><b> Why use Erenta as a lender?</b></h2> 
<br/>
    <strong> <p> When you choose our service you get the following benefits -:</p> </strong>
<br/>
      <ol>
          <div class="row">
              
              <div class="col-lg-3">
      <li><h5>You quickly make your money back on item by lending it out through Erenta.</h5></li>
      </div>
      <div class='col-lg-3'>
      <li><h5>By sharing with each other that we develop meaningful relationships and create effective local communities. It built trust and social barriers fall down.</h5> </li>
      </div>
      <div class='col-lg-3'>
      <li> <h5>By giving a quality product, reliable and convenient service with good communication the borrower will see you again.</h5></li>
      </div>
      <div class='col-lg-3'>
      <li><h5>Make world a efficient place for everyone and get paid within 10 days. </h5></li>
      </div>
              
          </div>
    </ol>
</div>
{% endblock %}

accounts/templates/accounts/supplier_bank_details.html
{% extends "supplier_base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/progressbar.css' %}">
<link rel="stylesheet" href="{% static 'css/form.css' %}">

<div class='col'>
<div class='container pt-3' style='background-color:#ffffff;'>
<div class='text-left'>
    <h5>Step 2 of 2 </h5>
</div>
    <div class="col-12 col-md-6 mx-auto">
       <h2 class='my-3 text-center'>Bank Details</h2> 
<form  method='POST' action='{% if action_url %} {{ action_url }}{% endif %}'>
     {% csrf_token %}
     {% if next_url %}
     <input type='hidden' name='next' value='{{ next_url }}' />
     {% endif %}
    

     {{ form|crispy }}<br/>
     
<div class='text-center'>
<button type='submit' class='btn-bg btn' style='background-color: #1daf9e; color:white;'> Launch your business </button>
</div>
<br/>
</form>
</div>
</div>


</div>
</div>
</div>


<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script><script  src="{% static 'js/vertical-nav.js' %}"></script>
{% endblock %}

accounts/templates/accounts/supplier_personal_details.html
{% extends "supplier_base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/progressbar.css' %}">
<link rel="stylesheet" href="{% static 'css/form.css' %}">

<div class='col'>
<div class='container pt-3' style='background-color:#ffffff;'>
    <div class='text-left'>
        <h5>Step 1 of 2</h5>
    </div>
    <div class="col-12 col-md-6 mx-auto">
    <h2 class='my-3 text-center'>Personal details</h2>
<form  method='POST' action='{% if action_url %} {{ action_url }}{% endif %}'>
     {% csrf_token %}
     {% if next_url %}
     <input type='hidden' name='next' value='{{ next_url }}' />
     {% endif %}
    

     {{ form|crispy }}<br/>
     
    <div class='text-center'>
<button type='submit' class='btn-bg btn' style='background-color: #1daf9e; color:white;'> Continue </button>
    </div>
    <br/>
</form>
</div>
</div>


</div>
</div>
</div>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script><script  src="{% static 'js/vertical-nav.js' %}"></script>
{% endblock %}

accounts/templates/accounts/supplier_register.html
{% extends "supplier_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
</br>

<div class='container'>
     <h2>Enter your business details</h2>
</br>
<form method='POST'>{% csrf_token %}
     {% if next_url %}
     <input type='hidden' name='next' value='{{ next_url }}' />
     {% endif %}
     {{ form|crispy }}<br/>
     <label for='email'>Email</label>
     <input type='text' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /> <br/>
             
<button type='submit' class='btn btn-success'>Submit</button>
</form>
</div>
{% endblock %}