Ecommerce_Intern/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path ,include
from django.contrib.auth.views import LogoutView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view,AddressUpdateView
#from carts.views import cart_home
#from products.views import ProductDetailSlugView
from accounts.views import LoginView,RegisterView,guest_register_view,BusinessDetailUpdateView,join_us_page,AddSupplierbankdetailView,AddSupplierpersonaldetailView,BankDetailUpdateView
from billing.views import payment_method_view,payment_method_createview,CardUpdateView
from products.views import SupplierHomeView,my_productsView,ProductDetailUpdateView,ReviewView,SupplierReviewView,SupplierProductListView,SupplierAddProductImageView,SupplierAddProductVariationsView,SupplierAddProductQuantityView,SupplierTagView,ProductRefundView,SupplierRentalPeriodView,load_sub_category,load_sub_sub_category
#from carts.views import cart_detail_api_view
#from products.views import OtherDetailFormView
from analytics.views import SalesView,SalesAjaxView,Supplier_SalesView,Supplier_SalesAjaxView
from .views import home_page, about_page, contact_page,notification_page,supplier_notification_page,GeneratePdf,GenerateSupplierPdf,landing_page,home_redirect,order_current_status_notification_page,order_notification_page,low_quantity_notification_page,supplier_order_current_status_notification_page
from orders.views import RequestCancelView
from django.conf.urls.i18n import i18n_patterns
from .views import change_language
admin.site.site_header = 'ShopNow Administration'
admin.site.site_title = 'ShopNow Administration'
admin.site.index_title = 'ShopNow Administration'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('change_language/', 
         change_language, 
         name='change_language'),
]


urlpatterns += i18n_patterns(
    
    
    path('', landing_page, name='landing-page'),
    path('home/',home_redirect, name='home-redirect'),
    path('home/Tokyo/',home_page, name='home'),
    path('home/Osaka/',home_page, name='home1'),
    path('home/Kyoto/',home_page, name='home2'),
    #path('selection_notification_page/',selection_of_notification_page,name='selection_notification_page'),
    path('notification_page/',notification_page,name='notification_page'),
    path('order_notification_page/',order_notification_page,name='order_notification_page'),
    path('order_current_status_notification_page/',order_current_status_notification_page,name='order_current_status_notification_page'),
    path('supplier_notification_page/',supplier_notification_page,name='supplier_notification_page'),
    path('low_quantity_notification_page/',low_quantity_notification_page,name='low_quantity_notification_page'),
    path('supplier_order_current_status_notification_page/',supplier_order_current_status_notification_page,name='supplier_order_current_status_notification_page'),
    path('contact/',contact_page, name='contact'),
    path('notification/', include(("notification.urls", 'notification'), namespace='notification')),
    path('cart/', include(("carts.urls", 'carts'), namespace='cart')),
    path('about/',about_page, name='about'),
    path('join-us/',join_us_page,name='join_us'),
    path('accounts/',RedirectView.as_view(url='/account')),
    path('accounts/',include(("accounts.passwords.urls"))),
    path('account/',include(("accounts.urls", 'accounts'), namespace='account')),
    path('manage/sales/',SalesView.as_view(),name='sales-analytics'),
    path('manage/sales/data/',SalesAjaxView.as_view(),name='sales-analytics-data'),
    path('supplier/sales/',Supplier_SalesView.as_view(),name='supplier-sales-analytics'),
    path('supplier/sales/data/',Supplier_SalesAjaxView.as_view(),name='supplier-analytics-data'),
    path('login/',LoginView.as_view(), name='login'),
    #path('loginsupplier/',SupplierLoginView.as_view(), name='login1'),
    #path('api/cart/',cart_detail_api_view, name='api_cart'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('addressupdate/<int:id>/', AddressUpdateView.as_view(), name='address_update_view'),
    #path('cart/transaction/', TransactionMessageView.as_view() , name='transactionmessage'),
    path('register/guest/',guest_register_view, name='guest_register'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('cardupdate/<int:id>/', CardUpdateView.as_view(), name='card_update_view'),
    # path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('register/',RegisterView.as_view(), name='register'),
    #path('logout_page/', logout_page, name='logout_page'),
    path('settings/',RedirectView.as_view(url='/account')),
    path('products/', include(("products.urls", 'products'), namespace='products')),
    path('orders/', include(("orders.urls", 'orders'), namespace='orders')),
    path('search/', include(("search.urls", 'search'), namespace='search')),
    path('category/', include(("category.urls", 'category'), namespace='category')),
    path('supplier/',SupplierHomeView.as_view(),name='supplier'),
    #path('add/',AddProductView.as_view(),name='add'),
    path('myproduct/',my_productsView.as_view(), name='myproduct'),
    path('updateproduct/<slug:slug>/',ProductDetailUpdateView.as_view(),name='update'),
    #path('products/<slug:slug>/',ProductDetailSlugView.as_view(),name='other'),
    path('request-refund/<int:id>/<slug:slug>/',RequestCancelView.as_view(),name='refund'),
    path('reviews/<int:id>/<slug:slug>/',ReviewView.as_view(),name='review'),
    path('product-refund/<int:id>/<slug:slug>/',ProductRefundView.as_view(),name='product-refund'),
    path('supplierreviews/',SupplierReviewView.as_view(),name='supplierreview'),
    path('businessdetailupdate/',BusinessDetailUpdateView.as_view(),name='businessdetailupdate'),
    path('bankdetailupdate/',BankDetailUpdateView.as_view(),name='bankdetailupdate'),
    path('addpersonaldetails/',AddSupplierpersonaldetailView.as_view(),name='addsupplierpersonaldetail'),
    path('addbankaccountdetails/',AddSupplierbankdetailView.as_view(),name='addsupplierbankdetail'),
    #path('add_product/',SupplierAddProductView.as_view(),name='addproduct'),
    path('add_product_details/',SupplierProductListView.as_view(),name='addproductdetails'),
    path('add_product_details/add_image/<int:id>/',SupplierAddProductImageView.as_view(),name='productimage'),
    path('add_product_details/add_variations/<int:id>/',SupplierAddProductVariationsView.as_view(),name='productvariations'),
    path('add_product_details/add_quantity/<int:id>/',SupplierAddProductQuantityView.as_view(),name='productquantity'),
    path('add_product_details/add_tags/<int:id>/',SupplierTagView.as_view(),name='producttags'),
    path('add_product_details/add_rental_period/<int:id>/',SupplierRentalPeriodView.as_view(),name='productrentalperiods'),
    path('<order_id>/pdf/',GeneratePdf.as_view(),name='pdf'),
    path('<id>/<order_id>/supplier/pdf/',GenerateSupplierPdf.as_view(),name='supplierpdf'),
    #prefix_default_language = False,
    path('load-sub_category/', load_sub_category, name='ajax_load_sub_category'), # AJAX
    path('load-sub_sub_category/', load_sub_sub_category, name='ajax_load_sub_sub_category'), # AJAX


)

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.contrib import admin
from django.urls import path
from .views import cart_home,checkout_home,checkout_done_view,add_to_cart,remove_cart,remove_all_items,payment_method_default_update_view,remove_coupon_view


urlpatterns = [
   
    path('',cart_home, name='home'),
    #path('<slug:slug>/',update_cart, name='update_cart'),
    path('remove/<int:id>/', remove_cart, name='remove_cart'),
    path('removeall/', remove_all_items, name='remove_all'),
    path('<int:id>/', add_to_cart, name='add_to_cart'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('checkout/', checkout_home, name='checkout'),
    path('reusecards/', payment_method_default_update_view, name='reusecard'),
    path('removecoupon/<int:id>', remove_coupon_view, name='removecoupon')
]

templates/base.html
{% load static i18n %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <title> {{ title }} </title>
    {% include 'base/css.html' %}
    {% include 'base/navbar.html' with brand_name='ShopNow' %}

    
    {% block base_head %} {% endblock %}
   </head>
  <body style="background-color: rgb(241, 241, 241);">
     <!-- <div class="mt-3 pt-2"> -->
    
    {% if messages %}
        {% for message in messages %}
      <div class='text-center'>
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message|safe }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
        {% endfor %}
    {% endif %}
    

    {% block content %}

    {% endblock %}
    {% include 'base/footer.html' %}
    
     {% include 'base/js.html' %}
  
     
     {% block javascript %}

     {% endblock %}

    

  </body>
    
   


</html>

templates/home_page.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% url 'account:home' as account_url %}
<title> Home Page!</title>
{% block base_head %}
     <link rel='stylesheet' href='{% static "css/test.css" %}' />
{% endblock %}

{% block content %}

{% if request.user.is_authenticated %}
<div class='col' style="background-color: white;">
   {{ premium_content }} {{ user.full_name }}!
  <!-- <a href='{% url "account:user-update" %}'>
    <img src="{% static 'img/a.jpg' %}" width=50px height="50px" style="float: right;"  class="rounded-circle" alt="...."> </a> -->
   
</div>
{% else %}
{% trans "For better experience please Login." %}
{% endif %}
   
    	<!--first slider -->
    <style>
      @media screen and (max-width: 600px) {
                .carr1 {
                 height: 20% !important;
  }
} 
    </style>

    		<div class="site-slider">
    			<div class="slider-one carr1">
            {% for crousel_image in crousel_images %}
            {% if crousel_image.image %}
            <div>
    					<img src='{{ crousel_image.image.url }}' class="img-fluid carr1" alt="Banner" />
    				</div>
            {% endif %}
            {% endfor %}
    				
    			</div>

    			<div class="slider-btn">
    				<span class="prev position-top"><i class="fas fa-chevron-left"></i> </span>
    				<span class="next position-top right-0"><i class="fas fa-chevron-right"></i> </span>
    			</div>
    		</div>
    	</div>
    	<!-- /firstslider -->
      
  <br/>
  <style>
 
  .responsive {
  position: relative !important;
  width: 100%;
  max-width: 400px;
  height: auto !important;
}
 @media only screen and (min-width: 1200px) {
                .carr {
                  padding-top: 2rem !important;
                  margin-left: 2rem; 
              }
              }
 @media screen and (max-width: 992px) {
                .carr {
                  padding-top: 4rem !important;
                }
              }

 @media screen and (max-width: 600px) {
                .carr {
                 padding-top: 3rem !important;
                 
  }
} 

  </style>
  <hr/>
      <h2 class="text-center"> {% trans "Popular Categories" %} </h2>
    	<!-- second slider -->

    	<div class="container-fluid">
    		<div class="site-slider-two">
    			<div class="row slider-two text-center">
            {% for category_image in category_images %}
            {% if category_image.image %}
            <div class="col-md-4 col-lg-4 text-center">
              <a href="{% url 'products:query' category_image.slug %}"> <img src='{{ category_image.image.url }}' class="responsive carr" alt="Product"/></a>
               <b>{% trans category_image.title %}</b>
             </div>
             {% endif %}
             {% endfor %}

    			</div>
    			<div class="slider-btn" style="color:brown">
    				<span class="prev position-top"><i class="fas fa-chevron-left fa-2x text-secondry"></i> </span>
    				<span class="next position-top right-0"><i class="fas fa-chevron-right fa-2x text-secondry"></i> </span>
    			</div>
    		</div>
      </div>
      
    	<!-- /second slider -->

                             <!-- Cards   -->
                             <br/>
                             
                             <hr/>
<h2 class='text-center'>{% trans "Top trending Products" %}</h2>
  <div class='container-fluid'>
{% include 'analytics/view-count.html' %}
     
</div>

{% endblock %}

templates/notification_home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static i18n %}
{% block content %}
<div class='container'>
        <h3 class='text-center'>{% trans "Notifications" %}</h3>
        <br/>
     
        <div class='row mt-1' style='height:2rem; margin-bottom:5rem;'>
                {% if a %} 
                <div class='col-4 text-center' style='background-color: white;'>
                        <a style='color:black; text-decoration: none;' href="{% url 'notification_page' %}">Erenta Notifications ({{ count }} unread)</a>
                </div>
                {% else %}
                <div class='col-4 text-center' style='background-color: #1daf9e;'>
                        <a style='color: white; text-decoration: none;' href="{% url 'notification_page' %}">Erenta Notifications ({{ count }} unread)</a>
                </div>
                {% endif %}
                
                {% if a1 %} 
                <div class='col-4 text-center' style='background-color:white;'> 
                        <a style='color:black; text-decoration: none;' href="{% url 'order_notification_page' %}"><b>Order's Notifications ({{ count1 }} unread) </b></a>
                </div>
                {% else %}
                <div class='col-4 text-center' style='background-color: #1daf9e;'> 
                        <a style='color:white; text-decoration: none;' href="{% url 'order_notification_page' %}">Order's Notifications ({{ count1 }} unread)</a>
                </div>
                {% endif %}
                {% if a2 %} 
                <div class='col-4 text-center' style='background-color:white;'> 
                <a style='color:black; text-decoration: none;' href="{% url 'order_current_status_notification_page' %}"><b>Order item's status Notifications ({{ count2 }} unread) </b></a>
                </div>
                {% else %}
                <div class='col-4 text-center' style='background-color: #1daf9e;'>
                <a style='color:white; text-decoration: none;' href="{% url 'order_current_status_notification_page' %}"> Order item's status Notifications ({{ count2 }} unread)</a>
                </div>
                {% endif %}
                
        </div>

{% if a and count > 0 or a1 and count1 > 0 or a2 and count2 > 0 %}  


        {% if notifications %}
        {% for n in notifications %}
        {% if n.seen %}

        <p><a href="{% url 'notification:show_notification' n.id %}"><font color='black'>Dear {{ n.user.full_name }}, {{ n.title }}</font></a> <div class='text-right' style='color:#1daf9e'>{{ n.timestamp }} </div></p>
        <hr/>

        {% else %}

        <p> <span class="badge badge-pill badge-warning">Unseen</span> <strong><a href="{% url 'notification:show_notification' n.id %}"><font color='black'>Dear {{ n.user.full_name }}, {{ n.title }}</font></a> <div class='text-right' style='color:#1daf9e'>{{ n.timestamp }} </div> </strong></p>
        <hr/>
        {% endif %}
        {% endfor %}
        {% if notifications.has_other_pages %}
                <ul class="pagination justify-content-center">
                {% if notifications.has_previous %}
                <li class='page-item'><a class='page-link' href="?page={{ notifications.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class='page-item'><span class='current'>&laquo;</span></li>
                {% endif %}
                {% for i in notifications.paginator.page_range %}
                {% if notifications.number == i %}
                        <li class='page-item active'><span class='step-links'>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                        <li class='page-item active'><a class='page-link' href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if notifications.has_next %}
                <li class='page-item'><a class='page-link' href="?page={{ notifications.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class='page-item'><span class='step-links'>&raquo;</span></li>
                {% endif %}
                </ul>
        {% endif %}
        {% endif %}

        {% if order_notifications %}
        {% for n1 in order_notifications %}
        {% if n1.seen %}

        <p><a href="{% url 'notification:show_order_notification' n1.id %}"><font color='black'>Dear {{ n1.billing_profile.user.full_name }}, Your Order (Id-:{{ n1.order_id }}) has been {{ n1.status }} successfully. </font></a><div class='text-right' style='color:#1daf9e'>{{ n1.timestamp }} </div></p>
        <hr/>
        {% else %}

        <p><span class="badge badge-pill badge-warning">Unseen</span> <strong><a href="{% url 'notification:show_order_notification' n1.id %}"><font color='black'>Dear {{ n1.billing_profile.user.full_name }}, Your Order (Id-:{{ n1.order_id }}) has been {{ n1.status }} successfully. </font></a><div class='text-right' style='color:#1daf9e'>{{ n1.timestamp }} </div></strong></p>
        <hr/>
        {% endif %}
        {% endfor %}
        {% if order_notifications.has_other_pages %}
                <ul class="pagination justify-content-center">
                {% if order_notifications.has_previous %}
                <li class='page-item'><a class='page-link' href="?page={{ order_notifications.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class='page-item'><span class='current'>&laquo;</span></li>
                {% endif %}
                {% for i in order_notifications.paginator.page_range %}
                {% if order_notifications.number == i %}
                        <li class='page-item active'><span class='step-links'>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                        <li class='page-item active'><a class='page-link' href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if order_notifications.has_next %}
                <li class='page-item'><a class='page-link' href="?page={{ order_notifications.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class='page-item'><span class='step-links'>&raquo;</span></li>
                {% endif %}
                </ul>
        {% endif %}
        {% endif %}


        <!-- {% if userorder_status_notifications %}
        {% for n3 in userorder_status_notifications %}
        {% if n3.seen %}

        <p><a href="{% url 'notification:userorder_status_notification' n3.id %}"><font color='black'>Dear {{ n3.cart.user.full_name }}, our Order (Id-:{% for item in n3.cart.order_set.all %}{{ item.order_id }} {% endfor %}) {{ n3.product }} has been {{ n3.order_confirmed }}. </font></a><div class='text-right' style='color:#1daf9e'>{{ n3.timestamp }} </div></p>
        <hr/>
        {% else %}

        <p><span class="badge badge-pill badge-warning">Unseen</span> <strong><a href="{% url 'notification:userorder_status_notification' n3.id %}"><font color='black'>Dear {{ n3.cart.user.full_name }}, Your Order (Id-:{% for item in n3.cart.order_set.all %}{{ item.order_id }} {% endfor %}) {{ n3.product }} has been {{ n3.order_confirmed }}. </font></a><div class='text-right' style='color:#1daf9e'>{{ n3.timestamp }} </div></strong></p>
        <hr/>
        {% endif %}
        {% endfor %}
        {% endif %} -->


        {% if item_current_status %}
        {% for n2 in item_current_status %}
        {% if n2.seen %}
                {% if n2.status == 'paid' %}
                <p><a href="{% url 'notification:order_item_status' n2.id %}"><font color='black'>Dear {{ n2.cart.user.full_name }}, Your Order (Id-:{% for item in n2.cart.order_set.all %}{{ item.order_id }} {% endfor %}) {{ n2.product }} has been {{ n2.order_confirmed }}. </font></a><div class='text-right' style='color:#1daf9e'>{{ n2.timestamp }}  </div> </p>
                {% else %}

                <p><a href="{% url 'notification:order_item_status' n2.id %}"><font color='black'>Dear {{ n2.user.full_name }}, Your product item {{ n2.product }} {% for item in n2.cart.cartitem_set.all %}   {% if item.variations.all %} 
                {% for subitem in item.variations.all %} {{ subitem.category|capfirst }} : {{ subitem.title|capfirst }} {% endfor %} {% endif %} {% endfor %}  is {{ n2.status }}, Thank you.</font></a><div class='text-right' style='color:#1daf9e'>{{ n2.timestamp }} </div></p>
                <hr/>
                {% endif %}
        {% else %}
                        {% if n2.status == 'paid' %}
                        <p><span class="badge badge-pill badge-warning">Unseen</span> <strong><a href="{% url 'notification:order_item_status' n2.id %}"><font color='black'>Dear {{ n2.cart.user.full_name }}, Your Order (Id-:{% for item in n2.cart.order_set.all %}{{ item.order_id }} {% endfor %}) {{ n2.product }} has been {{ n2.order_confirmed }}. </font></a><div class='text-right' style='color:#1daf9e'>{{ n2.timestamp }} </div></strong></p>
                        {% else %}

                        <p><span class="badge badge-pill badge-warning">Unseen</span> <strong><a href="{% url 'notification:order_item_status' n2.id %}"><font color='black'>Dear {{ n2.user.full_name }}, Your product item {{ n2.product }} {% for item in n2.cart.cartitem_set.all %}   {% if item.variations.all %} 
                        {% for subitem in item.variations.all %} {{ subitem.category|capfirst }} : {{ subitem.title|capfirst }} {% endfor %} {% endif %} {% endfor %}  is {{ n2.status }}, Thank you.</font></a><div class='text-right' style='color:#1daf9e'>{{ n2.timestamp }} </div></strong></p>
                        <hr/>
                        {% endif %}
        {% endif %}
        {% endfor %}
        {% if item_current_status.has_other_pages %}
                <ul class="pagination justify-content-center">
                {% if item_current_status.has_previous %}
                <li class='page-item'><a class='page-link' href="?page={{ item_current_status.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class='page-item'><span class='current'>&laquo;</span></li>
                {% endif %}
                {% for i in item_current_status.paginator.page_range %}
                {% if item_current_status.number == i %}
                        <li class='page-item active'><span class='step-links'>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                        <li class='page-item active'><a class='page-link' href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if item_current_status.has_next %}
                <li class='page-item'><a class='page-link' href="?page={{ item_current_status.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class='page-item'><span class='step-links'>&raquo;</span></li>
                {% endif %}
                </ul>
        {% endif %}
        {% endif %}


{% else %}
<h3 class='text-center'>There is no new notifications.</h3>

{% endif %}


</div>
{% endblock %}

templates/supplier_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <title> {{ title }} </title>
    {% include 'base/css.html' %}
    
    {% include 'base/supplier_navbar.html' with brand_name='ShopNow' %}
    
    {% block base_head %} {% endblock %}
    
   
  </head>
  <body>
   
    {% if messages %}
        {% for message in messages %}
      <div class='text-center pt-3'>
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
        {% endfor %}
    {% endif %}
   

    
    {% include 'base/supplier_vertical_navbar.html' %}   
    {% block content %}

    {% endblock %}
    {% include 'base/footer.html' %}
    
     {% include 'base/js.html' %}
  
     
     {% block javascript %}

     {% endblock %}

    

  </body>
    
   


</html>