Ecommerce_Intern/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path ,include
from django.contrib.auth.views import LogoutView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view,AddressUpdateView
#from carts.views import cart_home
#from products.views import ProductDetailSlugView
from accounts.views import LoginView,RegisterView,guest_register_view,BusinessDetailUpdateView,join_us_page,AddSupplierbankdetailView,AddSupplierpersonaldetailView,BankDetailUpdateView
from billing.views import payment_method_view,payment_method_createview,CardUpdateView
from products.views import SupplierHomeView,my_productsView,ProductDetailUpdateView,ReviewView,SupplierReviewView,SupplierProductListView,SupplierAddProductImageView,SupplierAddProductVariationsView,SupplierAddProductQuantityView,SupplierTagView,ProductRefundView,SupplierRentalPeriodView,load_sub_category,load_sub_sub_category
#from carts.views import cart_detail_api_view
#from products.views import OtherDetailFormView
from analytics.views import SalesView,SalesAjaxView,Supplier_SalesView,Supplier_SalesAjaxView
from .views import home_page, about_page, contact_page,notification_page,supplier_notification_page,GeneratePdf,GenerateSupplierPdf,landing_page,home_redirect,order_current_status_notification_page,order_notification_page,low_quantity_notification_page,supplier_order_current_status_notification_page
from orders.views import RequestCancelView
from django.conf.urls.i18n import i18n_patterns
from .views import change_language
admin.site.site_header = 'ShopNow Administration'
admin.site.site_title = 'ShopNow Administration'
admin.site.index_title = 'ShopNow Administration'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('change_language/', 
         change_language, 
         name='change_language'),
]


urlpatterns += i18n_patterns(
    
    
    path('', landing_page, name='landing-page'),
    path('home/',home_redirect, name='home-redirect'),
    path('home/Tokyo/',home_page, name='home'),
    path('home/Osaka/',home_page, name='home1'),
    path('home/Kyoto/',home_page, name='home2'),
    #path('selection_notification_page/',selection_of_notification_page,name='selection_notification_page'),
    path('notification_page/',notification_page,name='notification_page'),
    path('order_notification_page/',order_notification_page,name='order_notification_page'),
    path('order_current_status_notification_page/',order_current_status_notification_page,name='order_current_status_notification_page'),
    path('supplier_notification_page/',supplier_notification_page,name='supplier_notification_page'),
    path('low_quantity_notification_page/',low_quantity_notification_page,name='low_quantity_notification_page'),
    path('supplier_order_current_status_notification_page/',supplier_order_current_status_notification_page,name='supplier_order_current_status_notification_page'),
    path('contact/',contact_page, name='contact'),
    path('notification/', include(("notification.urls", 'notification'), namespace='notification')),
    path('cart/', include(("carts.urls", 'carts'), namespace='cart')),
    path('about/',about_page, name='about'),
    path('join-us/',join_us_page,name='join_us'),
    path('accounts/',RedirectView.as_view(url='/account')),
    path('accounts/',include(("accounts.passwords.urls"))),
    path('account/',include(("accounts.urls", 'accounts'), namespace='account')),
    path('manage/sales/',SalesView.as_view(),name='sales-analytics'),
    path('manage/sales/data/',SalesAjaxView.as_view(),name='sales-analytics-data'),
    path('supplier/sales/',Supplier_SalesView.as_view(),name='supplier-sales-analytics'),
    path('supplier/sales/data/',Supplier_SalesAjaxView.as_view(),name='supplier-analytics-data'),
    path('login/',LoginView.as_view(), name='login'),
    #path('loginsupplier/',SupplierLoginView.as_view(), name='login1'),
    #path('api/cart/',cart_detail_api_view, name='api_cart'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('addressupdate/<int:id>/', AddressUpdateView.as_view(), name='address_update_view'),
    #path('cart/transaction/', TransactionMessageView.as_view() , name='transactionmessage'),
    path('register/guest/',guest_register_view, name='guest_register'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('cardupdate/<int:id>/', CardUpdateView.as_view(), name='card_update_view'),
    # path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('register/',RegisterView.as_view(), name='register'),
    #path('logout_page/', logout_page, name='logout_page'),
    path('settings/',RedirectView.as_view(url='/account')),
    path('products/', include(("products.urls", 'products'), namespace='products')),
    path('orders/', include(("orders.urls", 'orders'), namespace='orders')),
    path('search/', include(("search.urls", 'search'), namespace='search')),
    path('category/', include(("category.urls", 'category'), namespace='category')),
    path('supplier/',SupplierHomeView.as_view(),name='supplier'),
    #path('add/',AddProductView.as_view(),name='add'),
    path('myproduct/',my_productsView.as_view(), name='myproduct'),
    path('updateproduct/<slug:slug>/',ProductDetailUpdateView.as_view(),name='update'),
    #path('products/<slug:slug>/',ProductDetailSlugView.as_view(),name='other'),
    path('request-refund/<int:id>/<slug:slug>/',RequestCancelView.as_view(),name='refund'),
    path('reviews/<int:id>/<slug:slug>/',ReviewView.as_view(),name='review'),
    path('product-refund/<int:id>/<slug:slug>/',ProductRefundView.as_view(),name='product-refund'),
    path('supplierreviews/',SupplierReviewView.as_view(),name='supplierreview'),
    path('businessdetailupdate/',BusinessDetailUpdateView.as_view(),name='businessdetailupdate'),
    path('bankdetailupdate/',BankDetailUpdateView.as_view(),name='bankdetailupdate'),
    path('addpersonaldetails/',AddSupplierpersonaldetailView.as_view(),name='addsupplierpersonaldetail'),
    path('addbankaccountdetails/',AddSupplierbankdetailView.as_view(),name='addsupplierbankdetail'),
    #path('add_product/',SupplierAddProductView.as_view(),name='addproduct'),
    path('add_product_details/',SupplierProductListView.as_view(),name='addproductdetails'),
    path('add_product_details/add_image/<int:id>/',SupplierAddProductImageView.as_view(),name='productimage'),
    path('add_product_details/add_variations/<int:id>/',SupplierAddProductVariationsView.as_view(),name='productvariations'),
    path('add_product_details/add_quantity/<int:id>/',SupplierAddProductQuantityView.as_view(),name='productquantity'),
    path('add_product_details/add_tags/<int:id>/',SupplierTagView.as_view(),name='producttags'),
    path('add_product_details/add_rental_period/<int:id>/',SupplierRentalPeriodView.as_view(),name='productrentalperiods'),
    path('<order_id>/pdf/',GeneratePdf.as_view(),name='pdf'),
    path('<id>/<order_id>/supplier/pdf/',GenerateSupplierPdf.as_view(),name='supplierpdf'),
    #prefix_default_language = False,
    path('load-sub_category/', load_sub_category, name='ajax_load_sub_category'), # AJAX
    path('load-sub_sub_category/', load_sub_sub_category, name='ajax_load_sub_sub_category'), # AJAX


)

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.contrib import admin
from django.urls import path
from .views import cart_home,checkout_home,checkout_done_view,add_to_cart,remove_cart,remove_all_items,payment_method_default_update_view,remove_coupon_view


urlpatterns = [
   
    path('',cart_home, name='home'),
    #path('<slug:slug>/',update_cart, name='update_cart'),
    path('remove/<int:id>/', remove_cart, name='remove_cart'),
    path('removeall/', remove_all_items, name='remove_all'),
    path('<int:id>/', add_to_cart, name='add_to_cart'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('checkout/', checkout_home, name='checkout'),
    path('reusecards/', payment_method_default_update_view, name='reusecard'),
    path('removecoupon/<int:id>', remove_coupon_view, name='removecoupon')
]

notification/urls.py
from django.urls import path
from django.contrib import admin
from .views import show_notification,delete_notification,show_order_notification,delete_order_notification,supplier_order_notification,delete_supplier_order_notification,low_quantity_supplier_notification,delete_supplier_lowquantity_notification,order_item_status,delete_order_item_status,supplier_order_item_status,supplier_delete_order_item_status
urlpatterns = [

   path('show/<int:notification_id>', show_notification, name='show_notification'),
   path('delete/<int:notification_id>', delete_notification, name='delete_notification'),
   path('order_show/<int:notification_id>', show_order_notification, name='show_order_notification'),
   path('delete_notification/<int:notification_id>', delete_order_notification, name='delete_order_notification'),
   path('supplier_order_show/<int:notification_id>', supplier_order_notification, name='supplier_order_notification'),
   path('delete_supplier_notification/<int:notification_id>', delete_supplier_order_notification, name='delete_supplier_order_notification'),
   path('low_quantity_show/<int:notification_id>', low_quantity_supplier_notification, name='supplier_quantity_notification'),
   path('delete_quantity_notification/<int:notification_id>', delete_supplier_lowquantity_notification, name='delete_supplier_quantity_notification'),
   path('order_item_status/<int:notification_id>', order_item_status, name='order_item_status'),
   path('delete_order_item_status/<int:notification_id>', delete_order_item_status, name='delete_order_item_status'),
   path('supplier_order_item_status/<int:notification_id>', supplier_order_item_status, name='supplier_order_item_status'),
   path('supplier_delete_order_item_status/<int:notification_id>', supplier_delete_order_item_status, name='supplier_delete_order_item_status'),
   # path('userorder_status_show/<int:notification_id>', user_order_status_notification, name='userorder_status_notification'),
   # path('delete_userorder_status_notification/<int:notification_id>', delete_user_order_status_notification, name='delete_userorder_status_notification'),


]

notification/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .models import Notification,Order_Notification,Supplier_Order_Notification,Order_current_status
from orders.models import Low_Quantity_Notification

# Create your views here.

def show_notification(request,notification_id):
    n = Notification.objects.get(id=notification_id)
    n.seen = True
    n.save()
    return render(request, 'notification/notification.html',{'notification': n})

def delete_notification(request, notification_id):
    n = Notification.objects.get(id = notification_id)
    n.viewed = True
    n.save()
    return redirect("notification_page")


def show_order_notification(request,notification_id):
    n1 = Order_Notification.objects.get(id=notification_id)
    n1.seen = True
    n1.save()
    return render(request, 'notification/order_notification.html',{'order_notification': n1})


def delete_order_notification(request, notification_id):
    n1 = Order_Notification.objects.get(id = notification_id)
    n1.viewed = True
    n1.save()
    return redirect("notification_page")

# def user_order_status_notification(request,notification_id):
#     n10 = User_Order_Status_Notification.objects.get(id = notification_id)
#     n10.seen = True
#     n10.save()
#     return render(request, 'notification/user_order_status.html',{'user_order_status': n10})

# def delete_user_order_status_notification(request, notification_id):
#     n10 = User_Order_Status_Notification.objects.get(id = notification_id)
#     n10.viewed = True
#     n10.save()
#     return redirect("notification_page")


def supplier_order_notification(request,notification_id):
    n2 = Supplier_Order_Notification.objects.get(id = notification_id)
    n2.seen = True
    n2.save()
    return render(request, 'notification/supplier_order_notification.html',{'supplier_order_notification': n2})


def delete_supplier_order_notification(request, notification_id):
    n2 = Supplier_Order_Notification.objects.get(id = notification_id)
    n2.viewed = True
    n2.save()
    return redirect("supplier_notification_page")

def low_quantity_supplier_notification(request,notification_id):
    n3 = Low_Quantity_Notification.objects.get(id = notification_id)
    n3.seen = True
    n3.save()
    return render(request, 'notification/low_quantity_notification.html',{'low_quantity_notification': n3})


def delete_supplier_lowquantity_notification(request, notification_id):
    n3 = Low_Quantity_Notification.objects.get(id = notification_id)
    n3.viewed = True
    n3.save()
    return redirect("supplier_notification_page")

def order_item_status(request,notification_id):
    n4 = Order_current_status.objects.get(id = notification_id)
    n4.seen = True
    n4.save()
    return render(request,'notification/order_item_status.html',{'order_item_status': n4})

def delete_order_item_status(request, notification_id):
    n4 = Order_current_status.objects.get(id=notification_id)
    n4.viewed = True
    n4.save()
    return redirect("notification_page")


def supplier_order_item_status(request,notification_id):
    n5 = Order_current_status.objects.get(id=notification_id)
    n5.supplier_seen = True
    n5.save()
    return render(request,'notification/supplier_order_item_status.html',{'supplier_order_item_status': n5})

def supplier_delete_order_item_status(request, notification_id):
    n5 = Order_current_status.objects.get(id=notification_id)
    n5.supplier_viewed = True
    n5.save()
    return redirect("supplier_notification_page")

notification/templates/notification/low_quantity_notification.html
{% extends "supplier_base.html" %}
{% block content %}

{% if low_quantity_notification.product.user == request.user %}

<div class='container' style='background-color: white;'>
  
  <br/>

  <div class='text-center'>  <h3> Low quantity </h3> </div>
 <br/>

<list class="list-group-item list-group-item-action">Dear {{ low_quantity_notification.product.user.full_name }},  Only {{ low_quantity_notification.quantity }} {{ low_quantity_notification.product }} are left. To Update quantity <a href="{% url 'products:quantity' low_quantity_notification.product.slug %}"> click here </a>.
<div class='text-right'> <a href='{% url "notification:delete_supplier_quantity_notification" low_quantity_notification.id %}'><i class='fa fa-trash' style="color: black;"></i></a></div>
</list>
  </div>
{% else %}
<h3 class='text-center'> You are not authenticated to see this content.</h3>
{% endif %}
{% endblock %}

notification/templates/notification/notification.html
{% extends "base.html" %}
{% block content %}
{% if notification.user == request.user %}
<div class='container' style='background-color: white;'>
  
  <br/>


  
<div class='text-center'>  <h3> {{ notification.title }} </h3> </div>
 <br/>
  <list class="list-group-item list-group-item-action">Dear {{ notification.user.full_name }}, Welcome to Erenta and {{ notification.message }}
<div class='text-right'> <a href='{% url "notification:delete_notification" notification.id %}'><i class='fa fa-trash' style="color: black;"></i></a></div>
</list>
  </div>
{% else %}

<h3 class='text-center'>Oops! You are not authenticated for this content.</h3>
{% endif %}



{% endblock %}

notification/templates/notification/order_item_status.html
{% extends "base.html" %}
{% block content %}

{% if order_item_status.user == request.user %}
<div class='container' style='background-color: white;'>
  
  <br/>

  
<div class='text-center'>  <h3> Status -: {{ order_item_status.status }} </h3> </div>
 <br/>
  <list class="list-group-item list-group-item-action">Dear {{ order_item_status.user.full_name }}, <a href="{% url 'orders:list' %}">Your product item {{ order_item_status.product }} </a>  {% for item in order_item_status.cart.cartitem_set.all %}   {% if item.variations.all %}  {% for subitem in item.variations.all %} {{ subitem.category|capfirst }} : {{ subitem.title|capfirst }} {% endfor %} {% endif %} {% endfor %}  has been {{ order_item_status.status }} successfully.
<div class='text-right'> <a href='{% url "notification:delete_order_item_status" order_item_status.id %}'><i class='fa fa-trash' style="color: black;"></i></a></div>
</list>
  </div>
{% else %}
<h3> You are not authenticated to see this content.</h3>
{% endif %}
{% endblock %}

notification/templates/notification/order_notification.html
{% extends "base.html" %}
{% block content %}


{% if order_notification.billing_profile.user == request.user %}

<div class='container my-2 py-4' style='background-color: white;'>
  
  <br/>

  <p style='color:#1daf9e;'>{{ order_notification.timestamp }}  </p>
<div class='text-center'>  <h3> {{ order_notification.title }} </h3> </div>
 <br/>
  <list class="list-group-item list-group-item-action">Dear {{ order_notification.billing_profile.user.full_name }}, {% if order_notification.status == 'paid' %}<a href="{% url 'orders:list' %}">Your Order(Id-: {{ order_notification.order_id }}) </a> {% else %} Your Order(Id-: {{ order_notification.order_id }}) {% endif %}has been {{ order_notification.status }} successfully.
<div class='text-right'> <a href='{% url "notification:delete_order_notification" order_notification.id %}'><i class='fa fa-trash' style="color: black;"></i></a></div>
</list>
  </div>
{% else %}
<h3 class='text-center'> Oops! you are not authenticated for this content. </h3>
{% endif %}
{% endblock %}

notification/templates/notification/supplier_order_item_status.html
{% extends "supplier_base.html" %}
{% block content %}

{% if supplier_order_item_status.product.user == request.user %}
<div class='container' style='background-color: white;'>
  
  <br/>

  
<div class='text-center'>  <h3> Status -: {{ supplier_order_item_status.status }} </h3> </div>
<hr/>
 <br/>
  <list class="list-group-item list-group-item-action">Dear {{ supplier_order_item_status.product.user.full_name }}, <a href="{% url 'orders:orders' %}">Your product item {{ supplier_order_item_status.product }} </a>  {% for item in supplier_order_item_status.cart.cartitem_set.all %}   {% if item.variations.all %}  {% for subitem in item.variations.all %}  {% if subitem.product.user == request.user %} {{ subitem.category|capfirst }} : {{ subitem.title|capfirst }} {% endif %} {% endfor %} {% endif %} {% endfor %}  is {{ supplier_order_item_status.status }} successfully.
<div class='text-right'> <a href='{% url "notification:supplier_delete_order_item_status" supplier_order_item_status.id %}'><i class='fa fa-trash' style="color: black;"></i></a></div>
</list>
  </div>
{% else %}
<h3 class='text-center'>You are not authenticated to see this content.</h3>
{% endif %}
{% endblock %}

notification/templates/notification/supplier_order_notification.html
{% extends "supplier_base.html" %}
{% block content %}
{% if supplier_order_notification.product.user == request.user %}
<div class='container' style='background-color: white;'>
  
  <br/>

  <div class='text-center'>  <h3> Item -: {{ supplier_order_notification.product }} </h3> </div>
 <br/>

 <list class="list-group-item list-group-item-action">Dear {{ supplier_order_notification.product.user.full_name }}, Congrates you received an Order<a href="{% url 'orders:orders' %}"> of  {{ supplier_order_notification.product }}  {% for item in supplier_order_notification.cart.cartitem_set.all %}   {% if item.variations.all %}  {% for subitem in item.variations.all %} {% if subitem.product.user == request.user %} {{ subitem.category|capfirst }} : {{ subitem.title|capfirst }} {% endif %} {% endfor %} {% endif %} {% endfor %}  </a>.
<div class='text-right'> <a href='{% url "notification:supplier_order_notification" supplier_order_notification.id %}'><i class='fa fa-trash' style="color: black;"></i></a></div>
</list>
  </div>

{% else %}
<h3 class='text-center'> You are not authenticated to see this content.</h3>
{% endif %}
{% endblock %}

notification/templates/notification/user_order_status.html
{% extends "base.html" %}
{% block content %}

{% if user_order_status.cart.user == request.user %}
<div class='container' style='background-color: white;'>
  
  <br/>

  
<div class='text-center'>  <h3> Status -: {{ user_order_status.status }} </h3> </div>
 <br/>
  <list class="list-group-item list-group-item-action">Dear {{ user_order_status.cart.user.full_name }}, <a href="{% url 'orders:list' %}">Your product item {{ user_order_status.product }} </a>  {% for item in user_order_status.cart.cartitem_set.all %}   {% if item.variations.all %}  {% for subitem in item.variations.all %} {{ subitem.category|capfirst }} : {{ subitem.title|capfirst }} {% endfor %} {% endif %} {% endfor %} for Order(order_id: {% for item in user_order_status.cart.order_set.all %}{{ item.order_id }} {% endfor %})  has been {{ user_order_status.order_confirmed }} successfully.
<div class='text-right'> <a href='{% url "notification:delete_userorder_status_notification" user_order_status.id %}'><i class='fa fa-trash' style="color: black;"></i></a></div>
</list>

  </div>
{% else %}
<h3> You are not authenticated to see this content.</h3>
{% endif %}
{% endblock %}